### ISSUE TITLE
Synchronization job progress

### ISSUE THREAD

**Issue by wzorgdrager** [fasten-project/synchronize-javacg#1]
For this synchronization job we will consider the following Kafka flows:
```
fasten.maven.pkg -> fasten.OPAL.out -> fasten.MetadataDBJavaExtension.out
fasten.maven.pkg -> fasten.RepoCloner.out 
```

I assume RapidPlugin is not interested in `MetadataDBPythonExtension` nor `MetadataDBPythonExtension`.

I will make the synchronisation based on the `fasten.MetadataDBJavaExtension.out` and `fasten.RepoCloner.out` topics, by joining both streams. The idea is to track both streams and when a record comes in (from either stream):
1. it's checked against current state and if the record already exists there, a new record is emitted containing both plugin outputs. 
2. if it’s not in the current state, it’s added to the state and kept there for a certain period (so that it can be enriched with output from the other stream). 

In general, I could identify the following scenarios/cases:

- A record is in the `fasten.maven.pkg` topic, but due to errors in RepoCloner and OPAL or MetadataPlugin it will never reach this synchronisation job. Although this is unfortunate, this is something we can’t solve in this job.
- A record is properly processed by RepoCloner, but for the same record OPAL or the MetadataPlugin fails. Therefore the output of the RepoCloner will be kept in state but will never be enriched with the output from the MetadataPlugin. At some point the state will expire. We can then still emit the RepoCloner output, but maybe to an error topic? 
- A record is properly processed by OPAL+MetadataPlugin, but for the same record the RepoCloner fails. Therefore the output of the MetadataPlugin will be kept in state but will never be enriched with the output from the RepoCloner. At some point the state will expire. We can then still emit the MetadataPlugin output, but maybe to an error topic? 
- A record is properly processed by OPAL+MetadataPlugin and by the RepoCloner. This is the ideal situation. A new record is emitted with both the RepoCloner output and MetadataPlugin output. 

Some open questions:
1. How long to keep state? I.e. what is the max difference in processing time between RepoCloner and OPAL + Metadata? If the TTL (time-to-live) for the state is too short, we might lose records. If it’s set too long, state will have a huge size and it will take a long time to mark a record ‘failed’. 
2. What is the desired behaviour for the scenarios where, for the same record, one of the plugins fails? Output to an error topic?
3. ~Is there a field (or another way) to extract a timestamp from for each plugin output? This is necessary for managing the state and doing the join.~

**Comment by MagielBruntink** [comment]
RapidPlugin is interested also in MetadataDBPythonExtension nor MetadataDBCExtension, but it's good to start with Java.

With respect to the open questions:
  1. What is the currently observed longest running time for OPAL? Would 24 hours really result in an unmanagbly large state?
  2. Yes, logging to error topic. For RapidPlugin we use 3 topics for output actually, out, log, and err, following FASTEN defaults. We should apply the same here I think.

**Comment by wzorgdrager** [comment]
Thanks for your input!
1) I think we have a max processing time for OPAL of 1 hour. Nevertheless, I think 24 hours should be do-able and we will be on the safe side then. 
2) Okay, I will use this error topic then.

I'll work on this the coming days and hope to have something to share somewhere next week. I'll let you know!

**Comment by wzorgdrager** [comment]
So I finished the implementation for this synchronization job. Fortunately, I was able to make this as generic as possible. With the help of some environment variables, we can easily port this sync job to work for other topics with other keys and other requirements. I still need some time to properly test this implementation before I can start working on a (proper) deployment. I think it will be completely done and finished somewhere next week. If you're interested, I visualized the dataflow of the current implementation: 

![sync_job (1)](https://user-images.githubusercontent.com/2283622/100748461-a1330400-33e3-11eb-9d3e-1989647e61da.png)

**Comment by gousiosg** [comment]
Looks great @wzorgdrager. The only change I would do is pass the options to the command line instead of env variables, for consistency with the remaining of FASTEN.

**Comment by cg122** [comment]
Looks great. Just curios about in what scenario it will be "Both states are empty"

**Comment by wzorgdrager** [comment]
> Looks great. Just curios about in what scenario it will be "Both states are empty"

Fair point. In theory, together with the 'both states filled' scenario, this scenario cannot happen. However, I did implement to handle these two situations gracefully in the case it does occur for whatever (unknown) reason.

**Comment by wzorgdrager** [comment]
The sync job is deployed on the cluster.
